name: GitHub Actions Demo
on: [ push ]
jobs:
    Test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: echo " the job by ${{github.push}} event."
      - run: python main.py
